/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Jni */

#ifndef _Included_org_example_Jni
#define _Included_org_example_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Jni
 * Method:    helloworld
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_example_Jni_helloworld
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
